const beaches = [
    {
        name: "Waikiki Beach",
        description: "For those who love the beach, look no further than Waikiki. With its long stretch of white sand and turquoise blue water, everyone enjoys this paradise for swimming, surfing, snorkeling, and more. From Hilton Hawaiian Village on the west side to Kapi’olani Park in the east, Waikiki boasts a beautiful tropical climate with tons of activities and events for all ages. Find more high-rises, high-end restaurants, and resorts pepper along this popular destination’s borders. It really should be known as Waikiki Beaches, with the many different sections that make up this two-mile stretch of white sand.  Together, these beach sections make what everyone refers to as Waikiki Beach, one of the busiest and most cosmopolitan spots in Oahu where a plethora of activities geared towards tourists seem to go on all day and most of the night. Whether you are looking forward to surfing, canoe paddling, snorkeling, swimming, boogie boarding, sand combing, catching a golden tan, people watching, or marveling at a few beautiful Waikiki sunsets, it’s very easy to have a good time on the different areas of Waikiki Beach.",
    },
    {
        name: "Makena Beach",
        description: "Makena Beach State Park is one of Maui's signature beaches. With white sands extending nearly 2/3 of a mile long, it is one of the largest, undeveloped beaches in Maui. Enjoy relaxing on the beach with only nature in sight. Nestled between two black-lava outcroppings, Makena offers protection from the trade winds and provides great views of the islands of Molokini and Kahoolawe. The area is divided into two beaches known as Big Beach and Little Beach. Big Beach is located south of Wailea near the Makena Beach and Golf Resort and provides a secluded alternative to more crowded beaches in Kaanapali and Lahaina. Little Beach is a small cove without amenities and no lifeguard. Although state park regulations prohibit nudity, Little Beach is frequently used as a nude beach.",
    },
];
export { beaches }