const volcanoes = [
    {
        name: "Hawaii Volcanoes National Park",
        description: "Hawaii Volcanoes National Park encompasses 335,259 acres or about 523 square miles from the summit of Maunaloa to the sea (by comparison, the island of Oahu is 597 square miles). Discover 150 miles of hiking trails through volcanic craters, scalded deserts and rainforests, as well as a visitor center, petroglyphs and two active volcanoes: Maunaloa, which last erupted in 1984 and and Kilauea which last erupted in 2018 (1983-2018). Kilauea is often called 'the world's only drive-in volcano.' At one time, this prolific volcano produced 250,000-650,00 cubic yards of lava per day - enough to resurface a 20-mile-long, two-lane road each day. As of January 1983, more than 875 acres of new land has been created on the island of Hawaii.The extraordinary natural diversity of the park was recognized in 1980 when it was named a World Biosphere Site by UNESCO and in 1987 when the park was honored as a World Heritage Site.",
    },
    {
        name: "Diamond Head",
        description: "The unique profile of Diamond Head (Lē‘ahi) sits prominently near the eastern edge of Waikiki’s coastline. Hawaii’s most recognized landmark is known for its historic hiking trail, stunning coastal views, and military history. Diamond Head State Monument encompasses over 475 acres, including the interior and outer slopes of the crater.This broad, saucer-shaped crater was formed about 300,000 years ago during a single, explosive eruption that sent ash and fine particles in the air. As these materials settled, they cemented together into a rock called tuff, creating the crater, which is visible from the trail in the park. Most of the vegetation and birds were introduced in the late 1800s to early 1900s.The trail to the summit of Lē‘ahi was built in 1908 as part of Oahu’s coastal defense system. The 0.8 mile hike from trailhead to the summit is steep and strenuous, gaining 560 feet as it ascends from the crater floor. The walk is a glimpse into the geological and military history of Diamond Head. A concrete walkway built to reduce erosion shifts to a natural tuff surface about 0.2 mile up the trail with many switchbacks traversing the steep slope of the crater interior. The ascent continues up steep stairs and through a lighted 225-foot tunnel to enter the Fire Control Station completed in 1911. Built on the summit, the station directed artillery fire from batteries in Waikiki and Fort Ruger outside Diamond Head crater. At the summit, you’ll see bunkers and a huge navigational lighthouse built in 1917. The postcard view of the shoreline from Koko Head to Wai‘anae is stunning, and during winter, may include passing humpback whales.",
    },
];
export { volcanoes }